module.exports = {
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#16161a",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#d4d4d8",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "outline": "#9c8f7a",
        "outline-variant": "#4f4634",
        "surface-tint": "#f6be3b",
        "primary": "#ffe1aa",
        "on-primary": "#402d00",
        "primary-container": "#daa520",
        "on-primary-container": "#6d4f00",
        "inverse-primary": "#7a5900",
        "secondary": "#c8c5cd",
        "on-secondary": "#303036",
        "secondary-container": "#47464d",
        "on-secondary-container": "#b7b4bc",
        "tertiary": "#d8e6ff",
        "on-tertiary": "#01315c",
        "tertiary-container": "#a8cbff",
        "on-tertiary-container": "#315583",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdea1",
        "primary-fixed-dim": "#f6be3b",
        "on-primary-fixed": "#261900",
        "on-primary-fixed-variant": "#5c4200",
        "secondary-fixed": "#e4e1e9",
        "secondary-fixed-dim": "#c8c5cd",
        "on-secondary-fixed": "#1b1b21",
        "on-secondary-fixed-variant": "#47464d",
        "tertiary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#a6c9fc",
        "on-tertiary-fixed": "#001c39",
        "on-tertiary-fixed-variant": "#224874",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#3a342a",
        "primary-bright": "#c4941d"
},
      fontFamily: {
        headline: ["Archivo Narrow", "Arial Narrow", "sans-serif"],
        body: ["Space Grotesk", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
},
      spacing: {
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "2xl": "3rem",
        "3xl": "5rem"
},
      maxWidth: {
        "design-grid": "1200px",
      },
    },
  },
};
